### ISSUE TITLE
[BUG] Inconsistent fonts 

### ISSUE THREAD

**Issue by keckrich** [Martin-Pitt/dsp-prod-ratios#45]
When a recipe has an ingredient whose number of required buildings has a repeating number, the font for the decimal is different. An example is EM-rail ejectors set to make 10 per min with MK II assemblers 

![image](https://github.com/Martin-Pitt/dsp-prod-ratios/assets/25182466/24c0a020-dd07-4ba6-a65f-4efdbb55026f)

**Comment by Martin-Pitt** [comment]
It seems like the font doesn't support the unicode character I was trying to use here.

I personally use ellipsis to indicate repeating numbers but wanted to try use a more compact symbol.
Looks like there are also many different ways indicate repeating numbers that various per country which makes a bit more tricky than I thought: https://en.wikipedia.org/wiki/Repeating_decimal#Background

Went with using a text decoration overline for now like wikipedia does for the vinculum. Although the overline is being rendered way too high, was not able to adjust this. May have to fix this later by rendering the horizontal line using a pseudo element instead.
